# Generated by Django 4.0.10 on 2025-03-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='cantidad',
            field=models.IntegerField(verbose_name=10),
        ),
        migrations.AlterField(
            model_name='registro',
            name='lote',
            field=models.IntegerField(verbose_name=3),
        ),
    ]
