# Generated by Django 4.0.10 on 2025-03-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_alter_registro_cantidad_alter_registro_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registro',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='lote',
            field=models.IntegerField(),
        ),
    ]
