# Generated by Django 4.0.10 on 2025-04-03 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_alter_registro_cantidad_alter_registro_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre_cientifico', models.CharField(max_length=100)),
                ('nombre_comun', models.CharField(max_length=100)),
                ('ciclo_vida', models.CharField(max_length=40)),
                ('temperatura_optima', models.CharField(max_length=40)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.categoria')),
            ],
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
